# Generated by Django 5.0.6 on 2024-05-20 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorios', '0001_initial'),
        ('marcas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_activo', models.CharField(max_length=12)),
                ('nombre_activo', models.CharField(max_length=25)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('EN_REPARACION', 'En reparacion')], default='DISPONIBLE', max_length=16)),
                ('descripcion', models.TextField(blank=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='laboratorios.laboratoriosmodel')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='marcas.marcasmodel')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'db_table': 'Activos',
            },
        ),
    ]
